# Generated by Django 3.0.7 on 2020-07-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_burger_burgertopping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='burger', to='orders.burgerTopping'),
        ),
    ]
